# DataSource Config
#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql:///test01?userUnicode=true&characterEncoding=utf-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/test01
    username: root
    password: root

logging:
  level:
    com.example.demo: debug

# 输出具体的sql语句
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0